# Generated by Django 3.2.5 on 2021-12-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='accounts/profile_img/no_image.jpg', upload_to='accounts/profile_img'),
        ),
    ]
