# Generated by Django 3.2.5 on 2022-01-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220106_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='profile',
            name='long',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=8),
        ),
    ]
