# Generated by Django 3.2.5 on 2022-01-19 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_long_profile_lon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='lat',
            new_name='la',
        ),
    ]
