# Generated by Django 3.2.5 on 2022-01-19 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_lat_profile_la'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='la',
            new_name='long',
        ),
    ]
