# Generated by Django 3.2.5 on 2022-01-19 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_la_profile_long'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='lon',
            new_name='lat',
        ),
    ]
